[package]
name = "igd"
version = "0.7.1"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]
description = "Internet Gateway Protocol client"
homepage = "https://github.com/sbstp/rust-igd"
repository = "https://github.com/sbstp/rust-igd"
documentation = "https://docs.rs/igd/"
readme = "README.md"
keywords = ["igd", "upnp"]
license = "MIT"

[dependencies]
regex = "0.2"
xmltree = "0.7"
rand = "0.4"
lynx = "0.1"
futures = { version = "0.1", optional = true }
tokio-core = { version = "0.1", optional = true }
tokio-timer = { version = "0.1", optional = true }
tokio-retry = { version = "0.1", optional = true }

[dependencies.hyper]
version = "0.11"
default-features = false
optional = true

[features]
default = []
async = ["futures", "tokio-core", "tokio-timer", "tokio-retry", "hyper"]

[[example]]
name = "add_any_port"

[[example]]
name = "add_port"

[[example]]
name = "add_remove"

[[example]]
name = "async"
required-features = ["async"]

[[example]]
name = "external_ip"

[[example]]
name = "remove_port"
