[package]
name = "igd"
version = "0.8.2"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]
description = "Internet Gateway Protocol client"
homepage = "https://github.com/sbstp/rust-igd"
repository = "https://github.com/sbstp/rust-igd"
documentation = "https://docs.rs/igd/"
readme = "README.md"
keywords = ["igd", "upnp"]
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[dependencies]
xmltree = "0.8"
rand = "0.4"
attohttpc = { version = "0.4", default-features = false }
url = "1"
futures = { version = "0.1.26", optional = true }
tokio = { version = "0.1.18", optional = true }
tokio-retry = { version = "0.2.0", optional = true }
log = "0.4.6"
bytes = "0.4.12"
simplelog = "0.5.3"
lynx = "0.2.0"

[dependencies.hyper]
version = "0.12.28"
default-features = false
features = [ "runtime" ]
optional = true

[features]
default = []
async = ["futures", "tokio", "tokio-retry", "hyper"]

[[example]]
name = "add_any_port"

[[example]]
name = "add_port"

[[example]]
name = "add_remove"

[[example]]
name = "async"
required-features = ["async"]

[[example]]
name = "external_ip"

[[example]]
name = "remove_port"
