[package]
name = "igd"
version = "0.1.2"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]
description = "Internet Gateway Protocol client"
homepage = "https://github.com/SBSTP/rust-igd"
repository = "https://github.com/SBSTP/rust-igd"
readme = "README.md"
keywords = ["igd", "upnp"]
license = "MIT"

[dependencies]
hyper = "0.6.*"
regex = "*"
xml-rs = "*"
