[package]
name = "igd"
version = "0.0.1"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]
description = "Internet Gateway Protocol client"
homepage = "https://github.com/SBSTP/rust-igd"
repository = "https://github.com/SBSTP/rust-igd"
readme = "README.md"
keywords = ["igd", "upnp"]
license = "MIT"

[dependencies]
curl = "0.2.0"
regex = "0.1.15"
regex_macros = "0.1.8"
